### ISSUE TITLE
base64 decode feature change

### ISSUE THREAD

**Issue by maddie** [shawn1m/overture#21]
With commit aa57485, it seems that the base64 decode feature (for the base64 encoded file like `gfwlist` if I understand correctly) has been moved from runtime to compile time. Currently in my setup, I have a scheduled job that fetches the latest `gfwlist` daily and restart `overture`. Does that mean I will have to do the base64 decoding myself from now on?

If yes, it would be nice to take this to people's attention since they might have the same setup as mine.

**Comment by shawn1m** [comment]
Yeah, I'm trying to make overture become a more generic DNS software instead of being limited to several particular use, so some features will be moved out of the program itself. 

As for people's attention, I'll announce those changes when the new version is released.

Base64 encoded file is easy to be decoded by the `build.py` with a little changes.

**Comment by maddie** [comment]
Thanks. Good to know!

**Comment by shawn1m** [comment]
At this moment, maybe restore base64 feature would be better, I will consider it later.
322de02a73a8954a59edc70d2921ce220bebb691
